### ISSUE TITLE
有几个疑问

### ISSUE THREAD

**Issue by KillingMeNow** [rocketRobin/myrmec#2]
1 sniffer调用populate后,ComplexMetadatas集合始终为空
2 无法识别出jpg格式

 关于问题1,我在Record类中,修改iscomplexMetadata属性为{get;set;},然后修改从构造函数中初始化这个属性 并将FileTypes对应的Record修改之后,再运行并调用populate,ComplexMetadatas集合有了值
问题2 ,暂时没看明白代码,,水平有限 ^_^.jpg文件尝试过windows画图保存出的jpg和一些网上下载的图 都不能匹配成功

**Comment by rocketRobin** [comment]
1. 这个还没写完呢 ^_^
2. 这个有可能是因为文件头的问题，jpg有3种，ff d8 ff db ,还有一种中间有跳跃的，还有一种是 ff d8（其实这个是这几种共有的头），在现在的版本中只支持 ff d8 ff db 这种，但是jpg可能是ff d8 ?? ?? 这种，所以识别不了，下个版本支持跳字节和offset之后，应该就支持了，到时候我再测试一下，再通知你
![default](https://user-images.githubusercontent.com/9987850/36704482-82710d7c-1b9b-11e8-98e3-609a1a96edd2.png)

**Comment by rocketRobin** [comment]
现在你可以拉取最新的代码试试了，你 提的问题都解决了
