### ISSUE TITLE
Same Type File HEX data not same In FileTypes.cs

### ISSUE THREAD

**Issue by xingwen1987** [rocketRobin/myrmec#7]
[> 这是楼主的代码 <](https://github.com/rocketRobin/myrmec/blob/master/src/Myrmec/FileTypes.cs)
![image](https://user-images.githubusercontent.com/15207100/53221902-7fe9a380-36a6-11e9-889d-27c2050d20b9.png)
但是，我使用文件验真获取Bytes[]的代码，编写了一个HEX头文件工具，发现 zip 文件的头是这样的：
![image](https://user-images.githubusercontent.com/15207100/53221976-c5a66c00-36a6-11e9-8329-1410b70b8eb7.png)
[> HEX头文件工具源码 <](https://github.com/xingwen1987/DynaX/tree/master/Code/AspNetCore.DynaX.Myrmec)
[> 对MyRmec的封装源码 <](https://github.com/xingwen1987/DynaX/blob/master/Code/AspNetCore.DynaX/02-Extensions/DynaX.Extensions.File.Myrmec.cs)

**Comment by rocketRobin** [comment]
你采集的十进制的吧，转换成16进制的就一样了

**Comment by xingwen1987** [comment]
我也发现了，更换了转换方式，发现楼主的 Hex 是正确的。

[> 奉上 HEX 头文件提取工具源码 <](https://github.com/xingwen1987/DynaX/tree/master/Code/AspNetCore.DynaX.Myrmec)

**Comment by rocketRobin** [comment]
哈，谢谢 :smiley:
